"""Tags for inline DC"""
# General
australian = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "au",
    "australia",
    "sydney",
    "австралия",
    "сидней",
]
african = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "za",
    "africa",
    "south africa",
    "johannesburg",
    "африка",
    "южная африка",
    "йоханнесбург",
]
south_american = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "sa",
    "south america",
    "brazil",
    "sao paolo",
    "chile",
    "santiago",
    "peru",
    "lima",
    "argentina",
    "buenos aires",
    "южная америка",
    "бразилия",
    "сан-паулу",
    "сан паулу",
    "чили",
    "сантьяго",
    "перу",
    "лима",
    "аргентина",
    "буэнос-айрес",
    "буэнос айрес",
]
north_european = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "eu",
    "europe",
    "north europe",
    "sweden",
    "stockholm",
    "европа",
    "северная европа",
    "швеция",
    "стокгольм",
]
east_european = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "eu",
    "europe",
    "европа",
    "east europe",
    "austria",
    "vienna",
    "poland",
    "warsaw",
    "восточная европа",
    "австрия",
    "вена",
    "польша",
    "варшава",
]
west_european = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "eu",
    "europe",
    "европа",
    "west europe",
    "germany",
    "frankfurt",
    "spain",
    "madrid",
    "западная европа",
    "германия",
    "франкфурт",
    "испания",
    "мадрид",
]
northern_usa = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "na",
    "north america",
    "usa",
    "united states",
    "northcentral",
    "northeast",
    "northwest",
    "chicago",
    "sterling",
    "moses lake",
    "северная америка",
    "сша",
    "соединённые штаты",
    "северо-центр",
    "северо-восток",
    "северо-запад",
    "чикаго",
    "стерлинг",
    "мозес лейк",
]
southern_usa = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "na",
    "south america",
    "usa",
    "united states",
    "southeast",
    "southwest",
    "los angeles",
    "atlanta",
    "северная америка",
    "сша",
    "соединённые штаты",
    "юго-запад",
    "юго-восток",
    "лос-анджелес",
    "лос анджелес",
    "атланта",
]
chinese = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "china",
    "shanghai",
    "tianjin",
    "guangzhou",
    "азия",
    "китай",
    "шанхай",
    "тяньцзинь",
    "гуанчжоу",
]
emirati = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "emirates",
    "dubai",
    "азия",
    "эмираты",
    "дубай",
]
hong_kongese = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "hong kong",
    "азия",
    "гонконг",
]
indian = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "india",
    "mumbai",
    "chennai",
    "азия",
    "индия",
    "мумбаи",
    "ченнай",
]
japanese = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "japan",
    "tokyo",
    "азия",
    "япония",
    "токио",
]
singaporean = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "singapore",
    "азия",
    "сингапур",
]
south_korean = [
    "dc",
    "data center",
    "data centers",
    "дц",
    "дата центер",
    "дата центры",
    "дата-центер",
    "дата-центры",
    "as",
    "asia",
    "south korea",
    "seoul",
    "азия",
    "южная корея",
    "сеул",
]

###
gun_name_list = [
    "usp-s",
    "p2000",
    "glock-18",
    "dual berettas",
    "p250",
    "cz75-auto",
    "five-seven",
    "tec-9",
    "desert eagle",
    "r8 revolver",
    "mp9",
    "mac-10",
    "mp7",
    "mp5-sd",
    "ump-45",
    "p90",
    "pp-bizon",
    "famas",
    "galil ar",
    "m4a4",
    "m4a1-s",
    "ak-47",
    "aug",
    "sg 553",
    "ssg 08",
    "awp",
    "scar-20",
    "g3sg1",
    "nova",
    "xm1014",
    "mag-7",
    "sawed-off",
    "m249",
    "negev",
]
gun_id_list = [
    "usps",
    "p2000",
    "glock18",
    "dualberettas",
    "p250",
    "cz75auto",
    "fiveseven",
    "tec9",
    "deserteagle",
    "r8revolver",
    "mp9",
    "mac10",
    "mp7",
    "mp5sd",
    "ump45",
    "p90",
    "ppbizon",
    "famas",
    "galilar",
    "m4a4",
    "m4a1s",
    "ak47",
    "aug",
    "sg553",
    "ssg08",
    "awp",
    "scar20",
    "g3sg1",
    "nova",
    "xm1014",
    "mag7",
    "sawedoff",
    "m249",
    "negev",
]

full_list = [
    chinese,
    emirati,
    hong_kongese,
    indian,
    japanese,
    singaporean,
    south_korean,
    north_european,
    east_european,
    west_european,
    northern_usa,
    southern_usa,
    australian,
    african,
    south_american,
]

currency_names_en = {
    "USD": "U.S. Dollar",
    "GBP": "British Pound",
    "EUR": "Euro",
    "RUB": "Russian Ruble",
    "BRL": "Brazilian Real",
    "JPY": "Japanese Yen",
    "NOK": "Norwegian Krone",
    "IDR": "Indonesian Rupiah",
    "MYR": "Malaysian Ringgit",
    "PHP": "Philippine Peso",
    "SGD": "Singapore Dollar",
    "THB": "Thai Baht",
    "VND": "Vietnamese Dong",
    "KRW": "South Korean Won",
    "TRY": "Turkish Lira",
    "UAH": "Ukrainian Hryvnia",
    "MXN": "Mexican Peso",
    "CAD": "Canadian Dollar",
    "AUD": "Australian Dollar",
    "NZD": "New Zealand Dollar",
    "PLN": "Polish Zloty",
    "CHF": "Swiss Franc",
    "AED": "U.A.E. Dirham",
    "CLP": "Chilean Peso",
    "CNY": "Chinese Yuan",
    "COP": "Colombian Peso",
    "PEN": "Peruvian Sol",
    "SAR": "Saudi Riyal",
    "TWD": "Taiwan Dollar",
    "HKD": "Hong Kong Dollar",
    "ZAR": "South African Rand",
    "INR": "Indian Rupee",
    "ARS": "Argentine Peso",
    "CRC": "Costa Rican Colon",
    "ILS": "Israeli Shekel",
    "KWD": "Kuwaiti Dinar",
    "QAR": "Qatari Riyal",
    "UYU": "Uruguayan Peso",
    "KZT": "Kazakhstani Tenge",
}

currency_names_ru = {
    "USD": "Доллар США",
    "GBP": "Британский фунт",
    "EUR": "Евро",
    "RUB": "Российский рубль",
    "BRL": "Бразильский реал",
    "JPY": "Японская иена",
    "NOK": "Норвежская крона",
    "IDR": "Индонезийская рупия",
    "MYR": "Малайзийский ринггит",
    "PHP": "Филиппинское песо",
    "SGD": "Сингапурский доллар",
    "THB": "Тайский бат",
    "VND": "Вьетнамский донг",
    "KRW": "Южнокорейская вона",
    "TRY": "Турецкая лира",
    "UAH": "Украинская гривна",
    "MXN": "Мексиканское песо",
    "CAD": "Канадский доллар",
    "AUD": "Австралийский доллар",
    "NZD": "Новозеландский доллар",
    "PLN": "Польский злотый",
    "CHF": "Швейцарский франк",
    "AED": "Дирхам ОАЭ",
    "CLP": "Чилийское песо",
    "CNY": "Жэньминьби",
    "COP": "Колумбийское песо",
    "PEN": "Перуанский соль",
    "SAR": "Саудовский риял",
    "TWD": "Тайваньский доллар",
    "HKD": "Гонконгский доллар",
    "ZAR": "Южноафриканский рэнд",
    "INR": "Индийская рупия",
    "ARS": "Аргентинское песо",
    "CRC": "Коста-риканский колон",
    "ILS": "Израильский шекель",
    "KWD": "Кувейтский динар",
    "QAR": "Катарский риал",
    "UYU": "Уругвайское песо",
    "KZT": "Казахстанский тенге",
}
